<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_makeAppointment</name>
   <tag></tag>
   <elementGuidId>db8a8999-70ef-4cb3-a2b8-89c9e3c5dd58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
