<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_history</name>
   <tag></tag>
   <elementGuidId>e7d6c3a5-a771-4fec-9a5b-09de32f45bee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
